# Generated by Django 4.2 on 2023-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(max_length=40),
        ),
    ]
