# Generated by Django 4.2 on 2023-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newuser_email_alter_newuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='otp',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='newuser',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
