# Generated by Django 4.2 on 2023-04-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_newuser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='profileimage',
            new_name='image',
        ),
    ]
