# Generated by Django 4.2 on 2023-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_profileimage_newuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_baned',
            field=models.BooleanField(default=False),
        ),
    ]
