# Generated by Django 4.2 on 2023-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_newuser_is_baned'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='bancount',
            field=models.IntegerField(default=0),
        ),
    ]
