# Generated by Django 4.2 on 2023-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_newuser_bancount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='bancount',
            field=models.IntegerField(),
        ),
    ]
