# Generated by Django 4.2 on 2023-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_newuser_baned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='baned_time',
            field=models.DateTimeField(),
        ),
    ]
