# Generated by Django 4.2 on 2023-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_newuser_bancount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='baned_time',
            field=models.DateTimeField(null=True),
        ),
    ]
