# Generated by Django 4.2 on 2023-04-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_newuser_baned_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='bancount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
