# Generated by Django 4.2 on 2023-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_newuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='interviewlink',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
