# Generated by Django 4.2 on 2023-06-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_newuser_interviewlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='point',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
