# Generated by Django 4.2 on 2023-05-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0002_gamifiedcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamifiedcours',
            name='learningpath',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gamifiedcours', to='path.learningpath'),
            preserve_default=False,
        ),
    ]
