# Generated by Django 4.2 on 2023-05-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0004_learningpath_descreption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamifiedcours',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='gamifiedcours',
            name='points',
        ),
        migrations.RemoveField(
            model_name='gamifiedcours',
            name='start_date',
        ),
    ]
