# Generated by Django 4.2 on 2023-06-08 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('path', '0006_learningpath_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamifiedCoursParticipate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participate_result', models.IntegerField(default=0)),
                ('finaldate_participate', models.DateTimeField(blank=True, null=True)),
                ('gamifiedcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursParticipate', to='path.gamifiedcours')),
                ('participate_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursParticipate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-participate_result', 'finaldate_participate'),
            },
        ),
    ]
