# Generated by Django 4.2 on 2023-05-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_images_imagenumber_paragraph_paragraphnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
