# Generated by Django 4.2 on 2023-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challenges_descreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='is_planified',
            field=models.BooleanField(default=False),
        ),
    ]
