# Generated by Django 4.2 on 2023-05-11 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_sposorads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='format',
        ),
        migrations.CreateModel(
            name='ChallengeRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=255)),
                ('challenges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengerule', to='challenges.challenges')),
            ],
        ),
    ]
