# Generated by Django 4.2 on 2023-05-14 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_registre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registre',
            old_name='user',
            new_name='registre_by',
        ),
    ]
