# Generated by Django 4.2 on 2023-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_point',
            field=models.IntegerField(default=0),
        ),
    ]
