# Generated by Django 4.2 on 2023-05-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0002_gamifiedcours'),
        ('challenges', '0015_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='gamifiedcours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='path.gamifiedcours'),
        ),
        migrations.AlterField(
            model_name='task',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='challenges.challenges'),
        ),
    ]
