# Generated by Django 4.2 on 2023-05-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('challenges', '0016_task_gamifiedcours_alter_task_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='challenge_type',
            field=models.CharField(choices=[('challenge', 'challenge'), ('job', 'job')], default='challenge', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenges',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.joboffer'),
        ),
    ]
