# Generated by Django 4.2 on 2023-05-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('challenges', '0017_challenges_challenge_type_challenges_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='job.joboffer'),
        ),
    ]
