# Generated by Django 4.2 on 2023-05-24 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_alter_challenges_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='task_file',
            field=models.FileField(upload_to='task_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'rar'])]),
        ),
    ]
