# Generated by Django 4.2 on 2023-06-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0024_remove_video_video_url_video_task_vedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='challenges.challenges'),
            preserve_default=False,
        ),
    ]
