# Generated by Django 4.2 on 2023-06-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0025_answer_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='participate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='challenges.participate'),
        ),
    ]
