# Generated by Django 4.2 on 2023-06-03 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0030_alter_answer_myansewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='myansewer',
        ),
        migrations.AddField(
            model_name='answer',
            name='participate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='challenges.participate'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participate_answers', to='challenges.challenges'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participate_answers', to='challenges.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participate_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
