# Generated by Django 4.2 on 2023-06-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0035_alter_images_imagenumber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participate',
            options={'ordering': ('-participate_result', 'finaldate_participate')},
        ),
        migrations.AddField(
            model_name='participate',
            name='finaldate_participate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
