# Generated by Django 4.2 on 2023-06-08 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0007_gamifiedcoursparticipate'),
        ('challenges', '0036_alter_participate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='coursparticpate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='path.gamifiedcoursparticipate'),
        ),
    ]
