# Generated by Django 4.2 on 2023-06-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('path', '0007_gamifiedcoursparticipate'),
        ('challenges', '0037_answer_coursparticpate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='gamifiedcours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='path.gamifiedcours'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='challenges.challenges'),
        ),
    ]
