# Generated by Django 4.2 on 2023-05-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descreption', models.CharField(blank=True, max_length=800)),
                ('skillsrequirment', models.CharField(blank=True, max_length=800)),
                ('jobbenifits', models.CharField(blank=True, max_length=800)),
                ('employment_nedded', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
